"""Change foreignkey for relevance in table card to cascade on update

Revision ID: 360628a1fd85
Revises: fe47b29a3a73
Create Date: 2025-01-23 16:10:04.066102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "360628a1fd85"
down_revision: Union[str, None] = "fe47b29a3a73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "Card_id_relevance_fkey",
        "Card",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "Card_id_relevance_fkey",
        "Card",
        "Relevance",
        ["id_relevance"],
        ["id"],
        onupdate="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "Card_id_relevance_fkey",
        "Card",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "Card_id_relevance_fkey",
        "Card",
        "Relevance",
        ["id_relevance"],
        ["id"],
    )
    # ### end Alembic commands ###
