"""Create Tags-table and association toCards

Revision ID: 59ed6c5224c6
Revises: 7189825ff138
Create Date: 2025-01-02 10:11:09.540055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ed6c5224c6'
down_revision: Union[str, None] = '7189825ff138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('Card_has_Tag',
    sa.Column('id_card', sa.Integer(), nullable=False),
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_card'], ['Card.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tag'], ['Tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_card', 'id_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Card_has_Tag')
    op.drop_table('Tag')
    # ### end Alembic commands ###
