"""Add table card

Revision ID: d087462e039d
Revises:
Create Date: 2025-01-01 22:35:16.240863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d087462e039d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Card",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "word_type",
            sa.Enum(
                "NONE",
                "NOUN",
                "VERB",
                "ADJECTIVE",
                "ADVERB",
                "PRONOUN",
                "PREPOSITION",
                name="wordtype",
            ),
            nullable=True,
        ),
        sa.Column("german", sa.String(), nullable=False),
        sa.Column("italian", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("german", "italian", name="uq_german_italian"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
