name: Automate unit tests

on:
  push:

jobs:
  test_model_services:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]  
        python-version: [3.11, 3.12]
        
    # env:
    #   PYTHONPATH: ${{ github.workspace }}/src

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install `uv`
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv

      - name: Install dependencies with `uv`
        run: |
          uv sync

      - name: Add virtual environment to PYTHONPATH
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/src;${{ github.workspace }}/.venv/Lib/site-packages" >> $GITHUB_ENV

      # # Add src/ to PYTHONPATH
      # - name: Add src to PYTHONPATH
      #   run: |
      #     echo "Adding src to PYTHONPATH"
      #     echo "PYTHONPATH=$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

      # Verify the PYTHONPATH (print it out to logs)
      - name: Verify PYTHONPATH
        run: |
          echo "PYTHONPATH is: $PYTHONPATH"
          python -c "import sys; print('PYTHONPATH:', sys.path)"
          python -c "import database; print('Module imported successfully')"

      # Run all tests in test/unit dir, including all tests in its subdirectories
      - name: Run tests
        run: |
          pytest test/unit