name: Automate unit tests

on:
  push:

jobs:
  automate-unit-tests:
    name: python
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        # run: uv run pytest test/unit
        run: |
           uv run pytest --junitxml=pytest-report.xml test/unit
        continue-on-error: true

      - name: Save test results
        if: steps.test.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: pytest-report.xml