name: Automate unit tests

on:
  push:

jobs:
  test_model_services:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]  
        python-version: [3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install `uv`
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv

      - name: Install dependencies with `uv`
        run: |
          uv sync

      - name: Add src and virtual environment to PYTHONPATH
        run: |
          echo "PYTHONPATH=${{ github.workspace }}\\src;${{ github.workspace }}\\.venv\\Lib\\site-packages" >> $GITHUB_ENV

      - name: Verify PYTHONPATH and Import Modules
        env: # Use environment variables explicitly here
          PYTHONPATH: ${{ github.workspace }}/src;${{ github.workspace }}/.venv/Lib/site-packages
        run: |
          echo "PYTHONPATH is: $PYTHONPATH"
          python -c "import sys; print('PYTHONPATH:', sys.path)"
          python -c "import database; print('Module imported successfully')"
        
      - name: Activate virtual environment and run tests
        shell: pwsh
        run: |
          $env:PATH = "${{ github.workspace }}\.venv\bin;$env:PATH"
          pytest test/unit

      # - name: Run tests
      #   env:
      #     PYTHONPATH: ${{ github.workspace }}/src;${{ github.workspace }}/.venv/Lib/site-packages
      #   run: |
      #     pytest test/unit